export const apiURL = 'XXXXXXXXXXXXXXXXXX'

export const appId = 'XXXXXXXXXXXXXXXXXX'

export const JWTSharedSecret = { // This secret should NEVER be on th client side. The license JWT MUST be generated by your backend.
    id: 'XXXXXXXXXXXXXXXXXX',
    key: 'XXXXXXXXXXXXXXXXXX'
}